// ModulesLoader.h
#ifndef MODULESLOADER_H
#define MODULESLOADER_H

#include "Define.h"
#include "ScriptMgr.h"

extern void AddModulesScripts();

#endif // MODULESLOADER_H

// ModulesLoader.cpp.in.cmake
// This file is automatically generated by CMake
